AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: chapter2

Resources:

  Chapter2Resource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AwsLambdaTestFunction
      Runtime: java11
      MemorySize: 512
      Handler: fr.simplex_software.aws.lambda.functions.Chapter2Function::handleRequest
      CodeUri: target/chapter2.jar
