AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: chapter3
Resources:
  Chapter3Resource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Chapter3Function
      Runtime: java11
      MemorySize: 512
      Handler: fr.simplex_software.aws.lambda.functions.Chapter3Function::handleRequest
      CodeUri: target/chapter3.jar
  Chapter3StreamResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Chapter3StreamFunction
      Runtime: java11
      MemorySize: 512
      Handler: fr.simplex_software.aws.lambda.functions.Chapter3StreamFunction::handleRequest
      CodeUri: target/chapter3.jar
  Chapter3PojoResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Chapter3PojoFunction
      Runtime: java11
      MemorySize: 512
      Handler: fr.simplex_software.aws.lambda.functions.Chapter3PojoFunction::handleRequest
      CodeUri: target/chapter3.jar
  Chapter3PojoListResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Chapter3PojoListFunction
      Runtime: java11
      MemorySize: 512
      Handler: fr.simplex_software.aws.lambda.functions.Chapter3PojoListFunction::handleRequest
      CodeUri: target/chapter3.jar

