AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Chapter 4 samples
Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 10
    Tracing: Active
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket in which the OpenAPI specification is stored
Resources:
  SendMoneyRestAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        send-money-api
      StageName:
        dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Join:
                - ''
                - - 's3://'
                  - Ref: BucketName
                  - '/openapi.yaml'
  GetMoneyTransferOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetMoneyTransferOrdersFunction
      CodeUri: functions/target/chapter4.jar
      Handler: fr.simplex_software.aws.lambda.functions.GetMoneyTransferOrders::handleRequest
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET
  GetMoneyTransferOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetMoneyTransferOrderFunction
      CodeUri: functions/target/chapter4.jar
      Handler: fr.simplex_software.aws.lambda.functions.GetMoneyTransferOrder::handleRequest
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET
  CreateMoneyTransferOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        CreateMoneyTransferOrderFunction
      CodeUri: functions/target/chapter4.jar
      Handler: fr.simplex_software.aws.lambda.functions.CreateMoneyTransferOrder::handleRequest
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET
  UpdateMoneyTransferOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        UpdateMoneyTransferOrderFunction
      CodeUri: functions/target/chapter4.jar
      Handler: fr.simplex_software.aws.lambda.functions.UpdateMoneyTransferOrder::handleRequest
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET
  RemoveMoneyTransferOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        RemoveMoneyTransferOrderFunction
      CodeUri: functions/target/chapter4.jar
      Handler: fr.simplex_software.aws.lambda.functions.RemoveMoneyTransferOrder::handlerRequest
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET

