AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Chapter 4 samples
Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 10
    Tracing: Active
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket in which the OpenAPI specification is stored
Resources:
  SendMoneyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: send-money-queue
      DelaySeconds: 0
      VisibilityTimeout: 120
  #LambdaExecutionRole:
    #Type: AWS::IAM::Role
    #Properties:
      #AssumeRolePolicyDocument:
        #Version: '2012-10-17'
        #Statement:
          #- Effect: Allow
            #Principal:
              #Service:
                #- lambda.amazonaws.com
            #Action:
              #- sts:AssumeRole
      #Policies:
        #- PolicyName: allowSqs
          #PolicyDocument:
            #Version: '2012-10-17'
            #Statement:
              #- Effect: Allow
                #Action:
                  #- sqs:SendMessage
                  #- sqs:ReceiveMessage
                  #- sqs:DeleteMessage
                  #- sqs:GetQueueAttributes
                  #- sqs:ChangeMessageVisibility
                  #- xray:PutTraceSegments
                #Resource: !GetAtt SendMoneyQueue.Arn
  SendMoneyRestAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        send-money-api
      StageName:
        dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Join:
                - ''
                - - 's3://'
                  - Ref: BucketName
                  - '/openapi.yaml'
  GetMoneyTransferOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetMoneyTransferOrdersFunction
      CodeUri: functions/target/chapter6.jar
      Handler: fr.simplex_software.aws.lambda.functions.GetMoneyTransferOrders::handleRequest
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET
  GetMoneyTransferOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetMoneyTransferOrderFunction
      CodeUri: functions/target/chapter6.jar
      Handler: fr.simplex_software.aws.lambda.functions.GetMoneyTransferOrder::handleRequest
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET
  CreateMoneyTransferOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        CreateMoneyTransferOrderFunction
      CodeUri: functions/target/chapter6.jar
      Handler: fr.simplex_software.aws.lambda.functions.CreateMoneyTransferOrder::handleRequest
      #Role: !GetAtt LambdaExecutionRole.Arn
      Policies: AmazonSQSFullAccess
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET
  UpdateMoneyTransferOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        UpdateMoneyTransferOrderFunction
      CodeUri: functions/target/chapter6.jar
      Handler: fr.simplex_software.aws.lambda.functions.UpdateMoneyTransferOrder::handleRequest
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET
  RemoveMoneyTransferOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        RemoveMoneyTransferOrderFunction
      CodeUri: functions/target/chapter6.jar
      Handler: fr.simplex_software.aws.lambda.functions.RemoveMoneyTransferOrder::handlerRequest
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: SendMoneyRestAPI
            Path: /orders
            Method: GET
  # Current workaround needed if you want to use the APIGW Console Test button
  # See https://github.com/awslabs/serverless-application-model/issues/59#issuecomment-348709355
  ConfigLambdaPermissionForGetMoneyTransferOrdersFunction:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - SendMoneyRestAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetMoneyTransferOrdersFunction
      Principal: apigateway.amazonaws.com
  ConfigLambdaPermissionForGetMoneyTransferOrderFunction:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - SendMoneyRestAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetMoneyTransferOrderFunction
      Principal: apigateway.amazonaws.com
  ConfigLambdaPermissionForCreateMoneyTransferOrderFunction:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - SendMoneyRestAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateMoneyTransferOrderFunction
      Principal: apigateway.amazonaws.com
  ConfigLambdaPermissionForUpdateMoneyTransferOrderFunction:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - SendMoneyRestAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UpdateMoneyTransferOrderFunction
      Principal: apigateway.amazonaws.com
  ConfigLambdaPermissionForRemoveMoneyTransferOrderFunction:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - SendMoneyRestAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RemoveMoneyTransferOrderFunction
      Principal: apigateway.amazonaws.com
